export type TranscriptionResult = {
  rawText: string;
  cleanedText: string;
  language: string | null;
  provider: string;
  confidence: number | null;
  segments: unknown[];
};

export type SummaryResult = {
  shortSummary: string;
  detailedSummary: string;
  customerIssue: string | null;
  keyPoints: string[];
  equipmentMentioned: string[];
  promisesMade: string[];
  followUpNeeded: boolean;
  strategyUseCase: string | null;
  strategyApplications: string[];
};

export type ExtractedActionItem = {
  title: string;
  description: string | null;
  dueAt: string | null;
  priority: "low" | "normal" | "high" | "urgent";
};

type WhisperSegment = {
  id?: number;
  start?: number;
  end?: number;
  text?: string;
  [key: string]: unknown;
};

type WhisperResponse = {
  text?: string;
  language?: string;
  segments?: WhisperSegment[];
};

type AnthropicTextBlock = { type: "text"; text: string };
type AnthropicContentBlock = AnthropicTextBlock | { type: string; [key: string]: unknown };
type AnthropicResponse = {
  content?: AnthropicContentBlock[];
  error?: { message?: string };
};

const ANTHROPIC_URL = "https://api.anthropic.com/v1/messages";
const ANTHROPIC_MODEL = "claude-sonnet-4-6";
const ANTHROPIC_VERSION = "2023-06-01";

const PLACEHOLDER_TRANSCRIPTION: TranscriptionResult = {
  rawText:
    "Placeholder transcript. Connect OpenAI, Deepgram, AssemblyAI, or local Whisper before production use.",
  cleanedText:
    "Placeholder transcript. Connect a transcription provider before production use.",
  language: null,
  provider: "placeholder",
  confidence: null,
  segments: [],
};

const PLACEHOLDER_SUMMARY: SummaryResult = {
  shortSummary: "Placeholder summary.",
  detailedSummary:
    "This is a placeholder summary generated by the Hawk backend scaffold. Configure a summary provider before production use.",
  customerIssue: null,
  keyPoints: [],
  equipmentMentioned: [],
  promisesMade: [],
  followUpNeeded: false,
  strategyUseCase: null,
  strategyApplications: [],
};

function stripJsonFences(text: string): string {
  let trimmed = text.trim();
  if (trimmed.startsWith("```")) {
    trimmed = trimmed.replace(/^```(?:json)?\s*/i, "");
    if (trimmed.endsWith("```")) {
      trimmed = trimmed.slice(0, -3);
    }
  }
  return trimmed.trim();
}

function extractAnthropicText(payload: AnthropicResponse): string {
  const blocks = payload.content ?? [];
  for (const block of blocks) {
    if (block && block.type === "text" && typeof (block as AnthropicTextBlock).text === "string") {
      return (block as AnthropicTextBlock).text;
    }
  }
  throw new Error("Anthropic response contained no text content block");
}

async function callAnthropic(params: {
  system: string;
  user: string;
  maxTokens: number;
}): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error("ANTHROPIC_API_KEY is not set; cannot call Claude");
  }

  const res = await fetch(ANTHROPIC_URL, {
    method: "POST",
    headers: {
      "x-api-key": apiKey,
      "anthropic-version": ANTHROPIC_VERSION,
      "content-type": "application/json",
    },
    body: JSON.stringify({
      model: ANTHROPIC_MODEL,
      max_tokens: params.maxTokens,
      system: params.system,
      messages: [{ role: "user", content: params.user }],
    }),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Anthropic API error (${res.status}): ${errText}`);
  }

  const payload = (await res.json()) as AnthropicResponse;
  return extractAnthropicText(payload);
}

function asStringArray(value: unknown, max?: number): string[] {
  if (!Array.isArray(value)) return [];
  const out: string[] = [];
  for (const v of value) {
    if (typeof v === "string" && v.trim().length > 0) {
      out.push(v.trim());
    }
    if (max !== undefined && out.length >= max) break;
  }
  return out;
}

function asNullableString(value: unknown): string | null {
  if (typeof value === "string" && value.trim().length > 0) return value.trim();
  return null;
}

function asPriority(value: unknown): "low" | "normal" | "high" | "urgent" {
  if (value === "low" || value === "normal" || value === "high" || value === "urgent") {
    return value;
  }
  return "normal";
}

export async function transcribeAudio(input: {
  audio: ArrayBuffer;
  mimeType: string | null;
  fileName: string;
}): Promise<TranscriptionResult> {
  if (process.env.AI_TRANSCRIPTION_PROVIDER === "placeholder") {
    return { ...PLACEHOLDER_TRANSCRIPTION, provider: "placeholder" };
  }

  const baseUrl = process.env.WHISPER_URL ?? "http://192.168.1.194:8000";
  const endpoint = `${baseUrl.replace(/\/+$/, "")}/v1/audio/transcriptions`;
  const model = process.env.WHISPER_MODEL ?? "Systran/faster-whisper-medium";

  const form = new FormData();
  const blob = new Blob([input.audio], { type: input.mimeType ?? "audio/m4a" });
  form.append("file", blob, input.fileName);
  form.append("model", model);
  form.append("response_format", "verbose_json");

  const res = await fetch(endpoint, { method: "POST", body: form });
  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Whisper transcription failed (${res.status}): ${errText}`);
  }

  const payload = (await res.json()) as WhisperResponse;
  const text = payload.text ?? "";
  return {
    rawText: text,
    cleanedText: text,
    language: payload.language ?? null,
    provider: "faster-whisper",
    confidence: null,
    segments: payload.segments ?? [],
  };
}

export async function summarizeTranscript(input: {
  transcript: string;
}): Promise<SummaryResult> {
  if (process.env.AI_SUMMARY_PROVIDER === "placeholder") {
    return { ...PLACEHOLDER_SUMMARY };
  }

  const system = [
    "You summarize transcripts of business conversations, meetings, voice notes, and site visits.",
    "Return ONLY a JSON object — no prose, no markdown fences.",
  ].join(" ");

  const user = [
    "Summarize the following transcript. Return a single JSON object with exactly these fields:",
    "- shortSummary: string (1 sentence capturing the gist)",
    "- detailedSummary: string (2-3 sentences with the most important context)",
    "- customerIssue: string or null (any specific problem, complaint, or open question raised; null if none)",
    "- keyPoints: string[] (up to 6 important points from the conversation)",
    "- equipmentMentioned: string[] (concrete items, products, tools, or equipment named; empty array if none)",
    "- promisesMade: string[] (specific commitments any speaker made — what, by when; empty array if none)",
    "- followUpNeeded: boolean (true if there is at least one open action, decision, or commitment that needs follow-up)",
    "- strategyUseCase: string or null (one paragraph describing a concrete real-world scenario where this conversation's content directly applies — name the situation, the actors, and the outcome; null only if there is no actionable substance)",
    "- strategyApplications: string[] (3-5 concrete, specific ways the listener can apply what was discussed to their day-to-day work this week — each item should start with an imperative verb, e.g. 'Block 30 min on Friday to ...', 'Add a checklist item that ...')",
    "",
    "Transcript:",
    input.transcript,
  ].join("\n");

  const raw = await callAnthropic({ system, user, maxTokens: 1024 });
  const cleaned = stripJsonFences(raw);

  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(cleaned) as Record<string, unknown>;
  } catch (err) {
    throw new Error(
      `Failed to parse Claude summary JSON: ${(err as Error).message}. Raw: ${cleaned.slice(0, 500)}`,
    );
  }

  return {
    shortSummary: asNullableString(parsed.shortSummary) ?? "",
    detailedSummary: asNullableString(parsed.detailedSummary) ?? "",
    customerIssue: asNullableString(parsed.customerIssue),
    keyPoints: asStringArray(parsed.keyPoints, 6),
    equipmentMentioned: asStringArray(parsed.equipmentMentioned),
    promisesMade: asStringArray(parsed.promisesMade),
    followUpNeeded: parsed.followUpNeeded === true,
    strategyUseCase: asNullableString(parsed.strategyUseCase),
    strategyApplications: asStringArray(parsed.strategyApplications, 5),
  };
}

export async function extractActionItems(input: {
  transcript: string;
  summary: SummaryResult;
}): Promise<ExtractedActionItem[]> {
  if (process.env.AI_SUMMARY_PROVIDER === "placeholder") {
    return [];
  }

  const system = [
    "Extract concrete follow-up actions from this transcript.",
    "Each must be something a specific person needs to do.",
    "Return ONLY a JSON array — no prose.",
  ].join(" ");

  const user = [
    "Given the transcript and summary below, extract concrete follow-up actions.",
    "Return ONLY a JSON array of objects with these fields:",
    "- title: string (required, short imperative description)",
    "- description: string or null (extra context, if any)",
    "- dueAt: ISO 8601 string or null (ONLY set if the call explicitly mentions a date or relative date like 'tomorrow', 'next Tuesday')",
    "- priority: one of \"low\" | \"normal\" | \"high\" | \"urgent\" (default \"normal\")",
    "",
    "If there are no follow-up actions, return an empty array [].",
    "",
    "Summary context:",
    JSON.stringify(input.summary),
    "",
    "Transcript:",
    input.transcript,
  ].join("\n");

  const raw = await callAnthropic({ system, user, maxTokens: 1024 });
  const cleaned = stripJsonFences(raw);

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch (err) {
    throw new Error(
      `Failed to parse Claude action-items JSON: ${(err as Error).message}. Raw: ${cleaned.slice(0, 500)}`,
    );
  }

  if (!Array.isArray(parsed)) return [];

  const items: ExtractedActionItem[] = [];
  for (const entry of parsed) {
    if (!entry || typeof entry !== "object") continue;
    const obj = entry as Record<string, unknown>;
    const title = asNullableString(obj.title);
    if (!title) continue;
    items.push({
      title,
      description: asNullableString(obj.description),
      dueAt: asNullableString(obj.dueAt),
      priority: asPriority(obj.priority),
    });
  }
  return items;
}
