export type TranscriptionResult = {
  rawText: string;
  cleanedText: string;
  language: string | null;
  provider: string;
  confidence: number | null;
  segments: unknown[];
};

export type SummaryDomain =
  | "business"
  | "personal_growth"
  | "learning"
  | "creative"
  | "health_wellness"
  | "relationships"
  | "other";

export type SummaryResult = {
  domain: SummaryDomain;
  shortSummary: string;
  detailedSummary: string;
  customerIssue: string | null;
  keyPoints: string[];
  equipmentMentioned: string[];
  promisesMade: string[];
  followUpNeeded: boolean;
  strategyUseCase: string | null;
  strategyApplications: string[];
};

export type ExtractedActionItem = {
  title: string;
  description: string | null;
  dueAt: string | null;
  priority: "low" | "normal" | "high" | "urgent";
};

type WhisperSegment = {
  id?: number;
  start?: number;
  end?: number;
  text?: string;
  [key: string]: unknown;
};

type WhisperResponse = {
  text?: string;
  language?: string;
  segments?: WhisperSegment[];
};

type AnthropicTextBlock = { type: "text"; text: string };
type AnthropicContentBlock = AnthropicTextBlock | { type: string; [key: string]: unknown };
type AnthropicResponse = {
  content?: AnthropicContentBlock[];
  error?: { message?: string };
};

const ANTHROPIC_URL = "https://api.anthropic.com/v1/messages";
const ANTHROPIC_MODEL = "claude-sonnet-4-6";
const ANTHROPIC_VERSION = "2023-06-01";

const PLACEHOLDER_TRANSCRIPTION: TranscriptionResult = {
  rawText:
    "Placeholder transcript. Connect OpenAI, Deepgram, AssemblyAI, or local Whisper before production use.",
  cleanedText:
    "Placeholder transcript. Connect a transcription provider before production use.",
  language: null,
  provider: "placeholder",
  confidence: null,
  segments: [],
};

const PLACEHOLDER_SUMMARY: SummaryResult = {
  domain: "other",
  shortSummary: "Placeholder summary.",
  detailedSummary:
    "This is a placeholder summary generated by the Hawk backend scaffold. Configure a summary provider before production use.",
  customerIssue: null,
  keyPoints: [],
  equipmentMentioned: [],
  promisesMade: [],
  followUpNeeded: false,
  strategyUseCase: null,
  strategyApplications: [],
};

const ALLOWED_DOMAINS: ReadonlySet<SummaryDomain> = new Set<SummaryDomain>([
  "business",
  "personal_growth",
  "learning",
  "creative",
  "health_wellness",
  "relationships",
  "other",
]);

function asDomain(value: unknown): SummaryDomain {
  if (typeof value !== "string") return "other";
  const v = value.trim().toLowerCase();
  return (ALLOWED_DOMAINS as ReadonlySet<string>).has(v) ? (v as SummaryDomain) : "other";
}

function stripJsonFences(text: string): string {
  let trimmed = text.trim();
  if (trimmed.startsWith("```")) {
    trimmed = trimmed.replace(/^```(?:json)?\s*/i, "");
    if (trimmed.endsWith("```")) {
      trimmed = trimmed.slice(0, -3);
    }
  }
  return trimmed.trim();
}

function extractAnthropicText(payload: AnthropicResponse): string {
  const blocks = payload.content ?? [];
  for (const block of blocks) {
    if (block && block.type === "text" && typeof (block as AnthropicTextBlock).text === "string") {
      return (block as AnthropicTextBlock).text;
    }
  }
  throw new Error("Anthropic response contained no text content block");
}

async function callAnthropic(params: {
  system: string;
  user: string;
  maxTokens: number;
}): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error("ANTHROPIC_API_KEY is not set; cannot call Claude");
  }

  const res = await fetch(ANTHROPIC_URL, {
    method: "POST",
    headers: {
      "x-api-key": apiKey,
      "anthropic-version": ANTHROPIC_VERSION,
      "content-type": "application/json",
    },
    body: JSON.stringify({
      model: ANTHROPIC_MODEL,
      max_tokens: params.maxTokens,
      system: params.system,
      messages: [{ role: "user", content: params.user }],
    }),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Anthropic API error (${res.status}): ${errText}`);
  }

  const payload = (await res.json()) as AnthropicResponse;
  return extractAnthropicText(payload);
}

function asStringArray(value: unknown, max?: number): string[] {
  if (!Array.isArray(value)) return [];
  const out: string[] = [];
  for (const v of value) {
    if (typeof v === "string" && v.trim().length > 0) {
      out.push(v.trim());
    }
    if (max !== undefined && out.length >= max) break;
  }
  return out;
}

function asNullableString(value: unknown): string | null {
  if (typeof value === "string" && value.trim().length > 0) return value.trim();
  return null;
}

function asPriority(value: unknown): "low" | "normal" | "high" | "urgent" {
  if (value === "low" || value === "normal" || value === "high" || value === "urgent") {
    return value;
  }
  return "normal";
}

export async function transcribeAudio(input: {
  audio: ArrayBuffer;
  mimeType: string | null;
  fileName: string;
}): Promise<TranscriptionResult> {
  if (process.env.AI_TRANSCRIPTION_PROVIDER === "placeholder") {
    return { ...PLACEHOLDER_TRANSCRIPTION, provider: "placeholder" };
  }

  const baseUrl = process.env.WHISPER_URL ?? "http://192.168.1.194:8000";
  const endpoint = `${baseUrl.replace(/\/+$/, "")}/v1/audio/transcriptions`;
  const model = process.env.WHISPER_MODEL ?? "Systran/faster-whisper-medium";

  const form = new FormData();
  const blob = new Blob([input.audio], { type: input.mimeType ?? "audio/m4a" });
  form.append("file", blob, input.fileName);
  form.append("model", model);
  form.append("response_format", "verbose_json");

  const res = await fetch(endpoint, { method: "POST", body: form });
  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Whisper transcription failed (${res.status}): ${errText}`);
  }

  const payload = (await res.json()) as WhisperResponse;
  const text = payload.text ?? "";
  return {
    rawText: text,
    cleanedText: text,
    language: payload.language ?? null,
    provider: "faster-whisper",
    confidence: null,
    segments: payload.segments ?? [],
  };
}

export async function summarizeTranscript(input: {
  transcript: string;
}): Promise<SummaryResult> {
  if (process.env.AI_SUMMARY_PROVIDER === "placeholder") {
    return { ...PLACEHOLDER_SUMMARY };
  }

  const system = [
    "You summarize transcripts of any kind — business calls, meetings, voice notes, journal entries, self-reflections, study sessions, brainstorms, coaching, health check-ins, conversations with friends or family, or any other recording.",
    "First identify the domain of the recording from its content. Then write each output field with content appropriate to that domain — the field names below are intentionally generic; their meaning adapts to the domain.",
    "Do not force business framing onto a personal, learning, creative, health, or relationship recording. Do not force personal framing onto a business recording. Match the register of the transcript.",
    "Return ONLY a JSON object — no prose, no markdown fences.",
  ].join(" ");

  const user = [
    "Summarize the transcript below. Return a single JSON object with exactly these fields:",
    "",
    "- domain: one of \"business\" | \"personal_growth\" | \"learning\" | \"creative\" | \"health_wellness\" | \"relationships\" | \"other\".",
    "  Pick the single best fit based on what the speaker(s) are actually doing in the recording, not on superficial vocabulary.",
    "",
    "- shortSummary: string (1 sentence capturing the gist, in language that fits the domain)",
    "- detailedSummary: string (2-3 sentences with the most important context)",
    "",
    "- customerIssue: string or null. The central concern, question, or focus of the recording. Adapt the meaning:",
    "    business → a customer's problem, complaint, or open question",
    "    personal_growth → the central insight, struggle, or theme the speaker is sitting with",
    "    learning → the main question being explored or concept being worked through",
    "    creative → the core idea or problem being developed",
    "    health_wellness → the main symptom, concern, or observation",
    "    relationships → the central dynamic or unresolved issue between people",
    "    other → whatever the recording's main focus is",
    "  Null only if there is no central focus.",
    "",
    "- keyPoints: string[] (up to 6 important points, beats, or moments from the recording)",
    "",
    "- equipmentMentioned: string[]. Concrete named things — adapt the meaning to the domain:",
    "    business → products, tools, equipment, software",
    "    personal_growth → books, practices, habits, frameworks, people referenced",
    "    learning → concepts, sources, papers, courses, terms introduced",
    "    creative → references, influences, materials, techniques",
    "    health_wellness → exercises, foods, medications, metrics",
    "    relationships → names of people, places, shared activities",
    "    other → any concrete nouns worth remembering",
    "  Empty array if nothing concrete was named.",
    "",
    "- promisesMade: string[]. Specific commitments made by any speaker (what, by when when stated). Adapt the meaning:",
    "    business → commitments to customers, colleagues, or oneself in a work context",
    "    personal_growth → commitments the speaker made to themselves (e.g. \"I'm going to journal every morning this week\")",
    "    learning → study plans, practice commitments",
    "    creative → creative practice commitments (e.g. \"write for 20 min daily\")",
    "    health_wellness → routines, appointments, lifestyle commitments",
    "    relationships → commitments to another person or to the relationship",
    "    other → any specific \"I/we will do X\" statement",
    "  Empty array if none.",
    "",
    "- followUpNeeded: boolean (true if there is at least one open thread, decision, action, or commitment worth revisiting)",
    "",
    "- strategyUseCase: string or null. One paragraph describing a concrete real-world scenario where the content of this recording directly applies. Adapt the meaning:",
    "    business → a work situation, the actors, and the outcome",
    "    personal_growth → a life situation where applying this insight would make a difference",
    "    learning → a context where this knowledge would be used",
    "    creative → a project or piece this could feed into",
    "    health_wellness → a daily/weekly situation where this would matter",
    "    relationships → a specific upcoming interaction or recurring dynamic",
    "  Null only if there is no actionable substance.",
    "",
    "- strategyApplications: string[] (3-5 concrete, specific actions the listener can take this week to apply what was discussed). Each must start with an imperative verb. Match the domain — for personal_growth/learning/creative this is practice and habit; for business this is work moves; for health it is routines; for relationships it is specific upcoming conversations or check-ins.",
    "",
    "Transcript:",
    input.transcript,
  ].join("\n");

  const raw = await callAnthropic({ system, user, maxTokens: 1536 });
  const cleaned = stripJsonFences(raw);

  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(cleaned) as Record<string, unknown>;
  } catch (err) {
    throw new Error(
      `Failed to parse Claude summary JSON: ${(err as Error).message}. Raw: ${cleaned.slice(0, 500)}`,
    );
  }

  return {
    domain: asDomain(parsed.domain),
    shortSummary: asNullableString(parsed.shortSummary) ?? "",
    detailedSummary: asNullableString(parsed.detailedSummary) ?? "",
    customerIssue: asNullableString(parsed.customerIssue),
    keyPoints: asStringArray(parsed.keyPoints, 6),
    equipmentMentioned: asStringArray(parsed.equipmentMentioned),
    promisesMade: asStringArray(parsed.promisesMade),
    followUpNeeded: parsed.followUpNeeded === true,
    strategyUseCase: asNullableString(parsed.strategyUseCase),
    strategyApplications: asStringArray(parsed.strategyApplications, 5),
  };
}

export async function extractActionItems(input: {
  transcript: string;
  summary: SummaryResult;
}): Promise<ExtractedActionItem[]> {
  if (process.env.AI_SUMMARY_PROVIDER === "placeholder") {
    return [];
  }

  const system = [
    "Extract concrete follow-up actions from this transcript.",
    "Each must be something a specific person needs to do.",
    "Return ONLY a JSON array — no prose.",
  ].join(" ");

  const user = [
    "Given the transcript and summary below, extract concrete follow-up actions.",
    "Return ONLY a JSON array of objects with these fields:",
    "- title: string (required, short imperative description)",
    "- description: string or null (extra context, if any)",
    "- dueAt: ISO 8601 string or null (ONLY set if the recording explicitly mentions a date or relative date like 'tomorrow', 'next Tuesday')",
    "- priority: one of \"low\" | \"normal\" | \"high\" | \"urgent\" (default \"normal\")",
    "",
    "If there are no follow-up actions, return an empty array [].",
    "",
    "Summary context:",
    JSON.stringify(input.summary),
    "",
    "Transcript:",
    input.transcript,
  ].join("\n");

  const raw = await callAnthropic({ system, user, maxTokens: 1024 });
  const cleaned = stripJsonFences(raw);

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch (err) {
    throw new Error(
      `Failed to parse Claude action-items JSON: ${(err as Error).message}. Raw: ${cleaned.slice(0, 500)}`,
    );
  }

  if (!Array.isArray(parsed)) return [];

  const items: ExtractedActionItem[] = [];
  for (const entry of parsed) {
    if (!entry || typeof entry !== "object") continue;
    const obj = entry as Record<string, unknown>;
    const title = asNullableString(obj.title);
    if (!title) continue;
    items.push({
      title,
      description: asNullableString(obj.description),
      dueAt: asNullableString(obj.dueAt),
      priority: asPriority(obj.priority),
    });
  }
  return items;
}
